version: '3.3'
services:
  golang:
    image: "${DOCKER_IMAGE_GOLANG}"
    container_name: "${DOCKER_CONTAINER_API}"
    #restart: always
    depends_on:
      - mysql
    networks:
      - cc
    volumes:
      - "${PROJECT_DIR}:/go/src/app"
    environment:
      VIRTUAL_HOST: "${DOCKER_CONTAINER_API}"
  mysql:
    image: mysql
    container_name: "${DOCKER_CONTAINER_DB}"
    #restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - cc
  nginx-proxy:
    image: "${DOCKER_IMAGE_PROXY}"
    container_name: "${DOCKER_CONTAINER_PROXY}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - .development-ssl-certs:/etc/nginx/certs
    networks:
      - cc
networks:
  cc:
    driver: bridge
